src/pages/Result.tsx

1. 작업내용
- Result Page의 Mid의 높이 속성을 min-height에서 height로 변경했습니다.
- 기존에 윗부분이 잘리던 현상이 수정되었습니다.
2. 의견 필요
- 기존에 잘리던 부분이 정상적으로 출력되긴 하나 정확한 이유를 모르겠습니다. 기존에는 화면 비율100%로 볼 경우 윗부분이 잘려서 보였고, 화면 비율을 축소할 경우 잘린 부분이 정상적으로 보였습니다. 
DustState컴포넌트나 '지역별 미세먼지 농도 순위' 에 관한 내용이 그려지기 전에 Mid가 먼저 min-height = 100vh 로 그려지기 때문에 Mid 이후에 그려진 내용들이 화면 밖으로 밀려났던 것이라고 생각됩니다. 해당 내용과 관련해서 읽어 볼만한 자료나 설명을 알고 계신다면 알려주세요!

fix: Mid의 높이를 수정함.

---

src/components/Progress.tsx
src/hooks/useFetch.ts
src/pages/Result.tsx
src/type/index.ts

1. 작업내용
- Result Page에 함께 있던 useFetch 함수를 다시 분리했습니다.
- Choice 화면에서 선택한 도시와 상관없이 Result 화면 상단에 표기되는 값이 일정했었습니다. 이제는 선택한 도시에 대한 정보가 표기됩니다. 
이전에는 어느 도시를 선택하든 통신결과 0번 째 인덱스에 해당하는 정보(도시 이름 제외)가 표기되었습니다.
- Progress 컴포넌트의 계산 방법을 수정했습니다. 미세먼지 수치가 100을 넘어가는 경우 Progress bar가 화면 밖으로 나가는 현상이 있었습니다. 기상청 통계 결과 역대 가장 심했던 서울의 미세먼지 농도는 1060㎍/㎥ 이상 이었습니다. 이는 역대 가장 높은 수치 였으므로 특별한 경우가 아니라면 1000㎍/㎥ 가 넘는 경우는 자주 발생하지 않을것으로 사료됩니다.
이에 따라 Progress bar의 계산식을 1/1000 으로 계산하도록 수정했습니다. 
2. 의견 필요
- 데이터를 다시 패칭하여 useFetch의 data State를 갱신하는 reFetch 함수를 useFetch안에 만들고 싶었습니다. 그리고 ```return {data , refetch }``` 와 같은 모습으로 만드려했습니다 만, 받는 쪽에서 type 문제를 해결하지 못하여서 우선 제외하고 PR을 날립니다. promiseAll 의 사용도 처음이라 어떤 방식으로 구현해야 할지 의견 주시면 감사하겠습니다. 
- 서비스 제목이 '"랭킹"먼지' 이므로 미세 먼지 농도 순위와 맞게 result page가 보여져야 한다고 생각됩니다. '미세먼지' + '초미세먼지' 값 등 다양한 sort …

refactor: useFetch 분리 / result page 결과값 수정

---

src/components/Map/index.tsx

- close #33 
- 문제 상황
https://user-images.githubusercontent.com/76807107/230946979-c438f8be-1970-4db1-8623-ffec3dd47f15.mp4
- 문제 해결
https://user-images.githubusercontent.com/76807107/230947080-67296b01-6c8c-4b40-917d-cef4993c84e4.mp4
- useEffect를 하나의 컴포넌트에서 너무 많이 사용하고 있는데 어떻게 리팩토링하면 좋을까요...?
- 여러 마커를 한 번에 띄워야 하기 때문에 커스텀 오버레이 타입을 가진 배열에 마커들을 push한 후, 하나씩 순회하면서 지도에 마커를 띄우도록 했어요.
- 그리고 재생성되지 않도록 useEffect 훅의 cleanUp 함수를 사용해 언마운트될 때 마커를 제거했어요.
- 동영상처럼 airQuality API에서 NaN값이 반환되는 경우가 가끔 있는데 추후에 개선할게요. [이전 pr 리뷰 참고](https://github.com/tooooo1/dust-rating/pull/32#discussion_r1161468440)
- 이렇게 하는 게 맞는 건지.... 맞나요오오오오...?! 잘하고 있는 건가요...

fix: 마커가 계속 생성되는 문제 해결

---

src/api/airQuality.ts
src/components/Map/index.tsx

- close #36
- 제 생각에 가장 최신의 수치 데이터를 보여주기 위해서 마커는 항상 삭제된 다음에 새로운 마커로 대체되어야 한다고 생각했어요. 그런데 마커가 중복 생성되는 문제가 있었고 이 문제를 이전 pr에서 해결했다고 생각했는데 지도가 확대될 때 마커가 보이지 않는 문제가 있었어요. 
- 커스텀오버레이로 마커를 생성하고 위치시키는 로직을 분리하지 않고 하나로 합쳐서 그 문제를 해결할 수 있었어요.
- air quality API가 유효하지 않은 값을 반환하는 경우가 있었는데, 이는 각 지역의 수치 배열을 순회하면서 해당 수치값의 flag 값을 확인해 유효한 값만 반환하도록 수정했어요.
.

fix: air quality API의 NaN 반환값 없애기

---

src/pages/Result.tsx
src/type/index.ts

- close #12
result Page에서 [미세먼지 | 초미세먼지] 오름차순으로 정렬할 수 있습니다.
움짤에는 option 태그들이 안보이네요
1. sortCityDust라는 함수가 있는데 page를 구성하는 파일에 남겨둬도 될까? 하는 생각이 들어요.
2. selectedDust라는 state를 사용해서 선택된 [미세먼지 | 초미세먼지]를 파악하도록 했는데 더 좋은 방법이 있다면 알려주세요!
1. option의 style을 적용하는 부분에서 ```import styled from '@emotion/styled';```을 활용해서 style을 적용하려고 하면 적용되지 않아서 tsx에 일일히 따로 적용했는데 정확한 이유를 모르겠어요. Chakra UI 문서나 chatGPT에서 알려준 방법들 중에서도 적당한 방법이 없는것 같아서 질문드려요!
```
<option style={{ backgroundColor: '#44b7f7', color: '#ffffff' }}>
{FINE_DUST}
</option>
<option style={{ backgroundColor: '#44b7f7', color: '#ffffff' }}>
{ULTRA_FINE_DUST}
</option>
```
2. 먼지 농도순으로 정렬된 결과를 보여주는 부분에서 ```sortCityDust(cityGroup).map((city, cityIdx)``` 가 사용되요. 여기서 sorting을 진행하는 부분과 map메서드가  성격이 다르다고 생각해서 sort 부분만 함수로 분리했는데 map 까지 묶어서 함수로 분리하는 것이 가독성이나 이해하는 …

Refactor: 미세먼지 순서로 정렬되도록 변경

---

src/components/Map/index.tsx
src/styles/globalStyle.css

- close #47 
- 기존에 지도와 마커의 정보가 겹치는 문제가 있어 지역명을 마커 내부로 위치키도록 했어요.
- 하나의 마커에 너무 많은 정보가 들어갈 것 같아 미세먼지 수치 정보인지 초미세먼지 수치 정보인지는 따로 표기하지 않았어요. 추후에 지도의 하단 부분에 마커의 정보 구성?을 표시하면 좋을 것 같아요.
.

feat: 마커 내부에 지역명 정보 추가하기

---

src/components/Dust/DustState.tsx
src/components/Logo.tsx
src/components/Ranking/CityRank.tsx
src/components/Ranking/SidoRank.tsx
src/pages/Choice.tsx
src/pages/DustMap.tsx
src/pages/Ranking.tsx
src/styles/globalStyle.css

- close #54 
- 기존에 globalStyle.css에서 width에 관한 미디어쿼리가 적용되지 않고 있어 Logo.tsx에서 width를 600px인 37.5rem으로 고정 후 미디어쿼리까지 적용했어요.
- 그리고 globalStyle.css에 #root에 적용된 height: 100vh를 제거했어요.

refactor: Ranking 페이지 chakra-ui 적용하기

---

src/components/Dust/DustState.tsx
src/components/Map/index.tsx
src/hooks/useMap.ts

- close #57 
- 이제 지도 화면 첫 접속 시 사용자 디바이스 근처에 미세먼지 관측소가 있다면 마커가 바로 표기됩니다.
- 마커 클릭 시 상세정보 모달과 마커의 정보가 일치하지 않던 문제를 수정했습니다.
- 상세 정보 모달에서 미세먼지와 초미세먼지 수치가 정상적으로 표기되지 않던 문제를 수정했습니다.
- 지도를 축소 할 때 다른 sido가 지도에 표기 되면 해당 지역의 마커는 click 이벤트가 동작하지 않던 문제를 수정했습니다.
- DustState.tsx의 props들이 적절히 사용되고 있는 것 같지 않아서 수정했습니다.
- 지도에 마커가 바로 표기되기는 하나, 지도를 한 번 움직이거나 줌 인/아웃을 해야 클릭 이벤트가 정상동작합니다. 이벤트 리스너를 부착하는 useEffect의 deps를 [currentLocation, zoomLevel] 로 해놓은 상태인데 지도 화면 첫 입장시에도 click 이벤트가 발생하게 하려면 어떻게 해야할까요..? 컴포넌트가 마운트 될 때 event 리스너도 적용될 줄 알았는데 안되더라구요!

Refactor: dustmap page 수정,개선

---

src/apis/dustForecast.ts
src/components/Dust/DustState.tsx
src/components/Map/index.tsx
src/components/Ranking/RankItem.tsx
src/components/Ranking/SidoRank.tsx
src/pages/DustForecast.tsx
src/pages/Ranking.tsx
src/utils/dustGrade.ts

- close #61 
- 기상 예보 데이터 글자 수가 너무 적은 것 같아 informOverall 데이터 뿐만 아니라 informCause 데이터도 추가했어요.
- 기존에는 DustState 컴포넌트의 prop으로 fineDust, ultraFineDust, kindOfDust를 받고 있었어요. 근데 avg가 아닌 경우에도 fineDust, ultraFineDust 데이터를 모두 받는 것이 좋지 못하다고 생각해서 dustGrade라는 하나의 prop을 갖도록 수정했어요. 근데 prop을 넘겨줄 때 값을 계산해서 넘겨주는 게 맞는지는 잘 모르겠어요.
```typescript
// 평균 상태를 나타낼 때
<DustState dustGrade={Math.floor((fineDustGrade + ultraFineDustGrade) / 2)} />
// 평균 상태를 나타내지 않을 때
<DustState dustGrade={fineDustScale} />
<DustState dustGrade={ultraFineDustScale} />
```
DustState 컴포넌트에 타입스크립트를 봐주세요.

refactor: DustForcast 페이지 스타일 개선

---

index.html
src/App.tsx
src/components/DustForcast/DustChart.tsx
src/components/Logo.tsx
src/components/Map/index.tsx
src/components/common/DustLevel.tsx
src/components/common/DustState.tsx
src/main.tsx
src/pages/Choice.tsx
src/pages/Ranking.tsx
src/styles/globalStyle.css
src/styles/theme.ts
src/utils/constants/index.ts
src/utils/constants/map.ts

- close #95 
- 특정 지역의 미세먼지 농도에 따라 Ranking 페이지의 배경색 적용하기, 애니메이션 구현
- theme 상수를 이용해 기존 DUST_SCALE_COLOR 상수 제거
- 글로벌 스타일 수정 -> 불필요한 flex 스타일 제거
- 폰트 미적용 해결
https://user-images.githubusercontent.com/76807107/237034585-ed818385-aefe-4625-bc37-673e318cf047.mp4
- 배경색을 바꾸기 위해 글로벌 스타일을 고쳤습니다.... 다른 페이지 스타일도 수정해야해요.
- 챠크라 theme를 사용하는게 좋은지 아님 기존 상수를 활용하는게 좋은지?

feat: 특정 지역의 미세먼지 농도에 따른 Ranking 페이지 배경색 적용

---

src/components/DustForcast/CurrentDustInfo.tsx
src/components/common/AlertBox.tsx
src/pages/DustForecast.tsx

- close #88 
- 모바일 환경에서의 화면을 구성합니다.
[chrome-capture-2023-4-9.webm](https://user-images.githubusercontent.com/12118892/236880116-1b093740-dd64-41a7-8b56-f9420de4a930.webm)
- 화면 축소 시 'OOO의 미세먼지 농도는 다음과 같습니다.' 가 OOO 으로 동네 이름만 표기됩니다.
- 화면 축소 시 '시간별 미세먼지 농도 2023-05-09' 메시지가 사라집니다. 
- 화면 축소 시 일부 메시지가 어색하게 줄 바꿈 되던 현상을 수정했습니다. (폰트 크기 수정)
- 기존 페이지에서 2번 이상 반복되던 부분을 별도의 컴포넌트로 분리했습니다.
- 먼지 농도에 따른 배경색 변경은 현재 올라와있는 다른 PR이 머지되면 반영할 예정입니다.
- 원 페이지가 정보의 양이 많지 않고 차트의 경우도 가로 스크롤이 적용 되어 있어서 어느 부분에서 UI를 변경해야 할지 의견을 듣고 싶습니다. 화면이 작아지는 만큼 정보를 간결하고 한 눈에 보기 편하게 UI를 구성하면 좋을 것 같다고 생각중입니다.

refactor: dust-forecast 페이지 모바일 UI 수정

---

src/components/DustForcast/CurrentDustInfo.tsx
src/pages/DustForecast.tsx
src/pages/Ranking.tsx
src/utils/formaters.ts

- close #115 
- 특정 지역의 미세먼지 농도에 따른 배경색 적용
- 반응형 구현
- 24시(0시)일 때, 어제 날짜 데이터 보여주기
https://github.com/tooooo1/dust-rating/assets/76807107/0be55235-81c8-47fb-8967-ea352eccf6ae
- 차트 데이터의 경우, 특정 시각에 대한 데이터를 불러오는 것이 아니라 하루치 데이터를 가져오는 방식이라 다음과 같이 데이터가 넘어와요.
- 즉, 24시가 되는 경우, 0시 데이터가 없어서 기존에는 차트 데이터가 비워져 있었는데 이를 해결했어요.
- 예를 들면 16일 24시 -> 17시 0시 데이터가 없음.

feat: DustForecast 페이지에 특정 지역의 미세먼지 농도에 따른 배경색 적용

---

src/components/Ranking/SelectList.tsx
src/pages/Choice.tsx
src/pages/Ranking.tsx

- close #104 
- 이제 ranking 화면에서도 선택했던 sido를 변경할 수 있습니다.
- sido를 변경시 spinner가 전체 화면 크기로 나오던 현상을 수정하여 더 자연스럽게 변화하도록 하였습니다.
- 일반 변수로 사용되던 'dustAverageGrade'를 state로 변경하였습니다.
- select를 구현하는 부분이 2번 이상 반복되어서 SelectList.tsx로 분리하였습니다.
- 동일 화면에서 보여지는 정보만 바뀌는 만큼 사용자가 최대한 이질감을 안느꼈으면 좋겠다 라고 생각했습니다.(flickering 같은) 좀 더 개선되었으면 좋겠다 하는 부분에 대해서 말씀해주세요!
- 화면의 자연스러운 변화를 위하여 state와 useEffect를 추가하였는데 더 좋은 방법이 있는지 궁금합니다.
- useLocation()로 받아오는 initSelectedSido는 Ranking페이지를 처음 로드할 때 말고는 사용되지 않습니다. 제거할 수 있는 방법이 있을까요? props로 받아오는 방법을 생각해보아야 할까요?
- 사용자가 선택한 sido를 select option 중 가장 최상단에 오게 하려다보니 sidoNames를 정의하는 표현식이 깔끔하지 않아진것 같습니다. 더 좋은 표현방법이 있을까요?

feat: ranking 화면에서 sido를 변경할 수 있도록 수정.

---

src/components/Ranking/SelectList.tsx
src/pages/Ranking.tsx

- close #135 
- ranking 페이지에서 선택한 도시가 변경되면 쿼리도 변경됩니다.
[chrome-capture-2023-4-20.webm](https://github.com/tooooo1/dust-rating/assets/12118892/068683e4-b17e-44d9-91b8-91dda016ed31)
캡쳐에 주소창, select option들이 안나오네요..변경된 ui 확인용으로 봐주세요.
- sido를 변경하고 뒤로 가기를 수행하면 쿼리는 이전 것으로 변경되지만 화면엔 변화가 없어서 replace 옵션을 수정하여 뒤로가기를 실행했을 때 이전 페이지로 가도록 해놓았습니다.
```
setSearchParams({ place: nextSido }, { replace: true });
```

refactor: ranking 페이지 쿼리 변경, 스타일 변경

---

src/components/Map/index.tsx
src/components/common/Rank.tsx
src/pages/DustForecast.tsx
src/pages/Ranking.tsx
src/styles/theme.ts
src/utils/dustGrade.ts

- close #137 
- 미세먼지 농도 기준을 (미세먼지 농도 grade + 초미세먼지농도 grade)/2 에서 미세먼지 농도 grade로 변경합니다.
이제 미세먼지 오염도가 좀 더 적절하게 표현됩니다!
- 필요없는 함수들을 제거하면서 불필요한 useEffect가 제거되었습니다. 😀
```
useEffect(() => {
sidoDustInfo &&
setDustAverageGrade(
getDustAverageGrade(
sidoDustInfo.fineDustGrade,
sidoDustInfo.ultraFineDustGrade
)
);
}, [sidoDustInfo]);
```
- style theme의 backgroundColors에 None 상태의 색상이 추가되었습니다. none은 데이터가 없는 상태이므로 배경의 애니메이션이 필요하진 않을 것 같아서 간략하게 적용했습니다. 그러나 로딩중 색상이 기본(하늘색)으로 표기되는 현상이 있어 다음 pr 에서 확인해보겠습니다.

refactor: 미세먼지 기준 변경, 불필요한 함수 제거

---

src/components/Map/MarkerModalDustInfo.tsx
src/components/Map/index.tsx

- close #143 
- 마커의 모달에 표기되는 정보가 올바르게 표현되도록 수정했습니다.( grade 평균값 -> finedustGrade)
[chrome-capture-2023-4-20.webm](https://github.com/tooooo1/dust-rating/assets/12118892/f99b722c-dffb-46b5-9d00-77a221b94bf8)
- 미세 먼지 표기 방법을 바꾸는 과정에서 마커의 모달 부분이 누락되어 부분을 수정했습니다.

fix: 모달의 정보가 올바르게 표기되도록 수정

---

src/App.tsx
src/components/Logo.tsx
src/components/Ranking/CityRankItem.tsx
src/components/Ranking/CityRankList.tsx
src/components/Ranking/SidoRankItem.tsx
src/components/Ranking/SidoRankList.tsx
src/components/common/ListFallback.tsx
src/components/common/Rank.tsx
src/components/common/index.ts
src/pages/Choice.tsx
src/pages/CityRanking.tsx
src/pages/Ranking.tsx
src/pages/index.ts
src/types/dust.ts
src/utils/constants/animations.ts
src/utils/constants/dust.ts
src/utils/constants/index.ts
src/utils/constants/route.ts
src/utils/constants/sortDustList.ts
src/utils/sortDustList.ts
src/utils/validate.ts

- close #134 
- CityRanking 페이지에 선택한 도시의 지역별 미세먼지 순위 랜더링
https://github.com/tooooo1/dust-rating/assets/76807107/f92dec3d-fed8-4da5-981c-8dc0626ecef5
- CityRanking 페이지 추가 -> Ranking 페이지는 따로 건드리지 않았어요.
- 미세먼지, 초미세먼지 별 정렬하는 함수 sortDustList 생성
- ListFallback 컴포넌트 구현
- Ranking 컴포넌트는 '/ranking', CityRanking 컴포넌트는 '/ranking/:place'로 설정했어요.

refactor: CityRanking 페이지에 선택한 도시의 지역별 미세먼지 순위 랜더링

---

src/pages/Choice.tsx
src/pages/Ranking.tsx
src/styles/theme.ts

- close #139 
- 랭킹 페이지에서 시/도 변경 시 화면의 배경이 기본색으로 돌아갔다가 변하는 현상을 수정합니다.
[chrome-capture-2023-4-20.webm](https://github.com/tooooo1/dust-rating/assets/12118892/62c5f6cd-8be4-40b4-9d1c-5275fe130e39)
- 정확한 원인을 파악하지 못하여 임시 방편으로 useState를 사용하여 개선하였습니다. 문제점이 무엇인지 파악되면 재수정 하도록 하겠습니다.
- useState를 사용하여서 새로 선택한 시/도 정보를 활용하여 새로운 배경색을 계산하기 전까지 활용하도록 하였습니다.
- 정확히 왜? 이런 문제가 발생하는지 파악하지 못했습니다. 재랜더링이 일어나서 sidoDustInfo가 아직 없는 상황이라면 기본 값으로 설정한 ```theme.backgroundColors[DUST_GRADE[sidoDustInfo?.fineDustGrade ?? 0]]```에 해당하는 색상이 나올거라고 생각했는데 Logo 컴포넌트의 Box 엘리먼트의 bg색상이 나오더라구요.  아래 쪽에 존재하는 '지역별 미세 먼지 농도 순위' 에는 정상적으로 적용되것으로 보였습니다.

fix: 시/도 변경 시 화면 배경이 깜빡 거리던 현상 수정

---

src/components/Map/ControlButton.tsx
src/components/Map/index.tsx
src/components/Nav/NavButton.tsx
src/components/Nav/NavListItem.tsx
src/components/Nav/index.ts
src/components/common/NaviButton.tsx
src/components/common/index.ts
src/pages/CityRanking.tsx
src/pages/DustForecast.tsx
src/pages/SidoRanking.tsx
src/styles/globalStyle.css

- close #149
- 메인, 지도 페이지를 제외한 모든 페이지에 NaviBar가 적용됩니다. 지도 페이지에는 뒤로 가기 버튼만 추가되었습니다. 이제 페이지 내에서 클릭만을 통해서 모든 페이지를 왔다 갔다 할 수 있습니다! 야호!
[chrome-capture-2023-4-20.webm](https://github.com/tooooo1/dust-rating/assets/12118892/304eca6a-074f-47ed-ab41-7421501ff9a9)
- ~~아직 merge 되지 않은 branch의 작업들을 pull 한 뒤 작업해서 중복되는 file change가 많을 것 같습니다. 그래서 이전 pr이 merge 되면 해당 pr을 최신화 하고 활성화 할 계획인데 그래도 중복되는 file Change이 많다면......죄송합니다.~~
오! 이전 pr merge 되고 해당 pr에 pull 해주니까  file change가 17에서 10으로 줄어들었네요!
- 애니메이션 적용이 처음이라 어떤지 모르겠네요. (코드 측면에서도 잘 작성된 건지 잘 모르겠습니다 의견주세요!)
- 프로젝트를 진행하면서 구현한 컴포넌트가 아니고 2번 이상 반복되는 코드들은 컴포넌트나 상수로 사용하자고 기준을 잡고 있습니다. 이번 PR 에서는 NavListItem.tsx가 대표적인 예가 되겠네요. 지금 당장 가독성이나 코드 길이에서 차이가 나지 않더라도 추후에 관리가 편할거라는 생각이 들어서 이렇게 진행하고 있는데 '배보다 배꼽이 더 커지나?' 하는 생각도 드네요! 여러분의 생각은 어떠신가요?
- …

feat: NaviBar 적용

---

src/components/Map/index.tsx
src/components/Nav/NavButton.tsx
src/components/common/Rank.tsx
src/styles/globalStyle.css

- close #164 
- close #109
- 랭킹 페이지 -> 랭킹 리스트 라인 맞추기
- 지도 페이지 -> 모달 하단 닫기 버튼 삭제
- 지도 페이지 -> 이전 버튼 위치 변경
- 지도 페이지 -> 지도 커서 모양
- nav bar가 기본적으로 열려있게 했습니다.
- 긴 지명에 hover시 확인가능.

style: 랭킹 리스트 라인 정렬

---

.github/labels.yml
.github/workflows/assignor.yml
.github/workflows/labeler.yml

- close #181 
- GitHub 액션 중 `TimonVS/pr-labeler-action@v4`와 `hkusu/review-assign-action@v1` 실행 시 오류가 발생했습니다.
- "Resource not accessible by integration" 메시지와 "github-token"에 관한 문제가 나타났습니다.
- 이를 해결하기 위해 GitHub 토큰의 권한을 확인하고, .github 디렉토리의 설정 파일 경로와 내용을 점검했습니다.
(`.github` 라벨이 없었어서 추가했어요. 라벨러도 잘됩니다.)
- 액션의 오류를 성공적으로 해결했습니다.
- PR 라벨링 및 리뷰어 지정이 이제 자동으로 진행됩니다.

fix: GitHub 액션 오류 해결 및 PR 자동화 개선

---

src/components/Map/index.tsx

- close #179 
- 기존에 지도에서 sido 단위 마커를 클릭했을 때 `dust-forecast?sido=서울&city=서울` 과 같이 비정상적인 url로 이동하던 문제를 수정했습니다. 이제 sido 단위 마커를 클릭하면 `ranking/서울` 처럼 이동됩니다.
[chrome-capture-2023-7-8.webm](https://github.com/tooooo1/dust-rating/assets/12118892/8f616a09-a162-46a6-be1b-bdb081d62fb7)
- 클릭된 지역의 이름이 city라는 변수에 들어가 있기 때문에 sido 배열에서 city가 있다면 `ranking/city` 로 이동하도록 했는데 더 좋은 방법이 있을까요?

Fix: sido 단위 마크를 클릭하면 해당 지역 랭킹 페이지로 이동
